name: Build Run and Test
'on':
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8


      - name: build test
      run: g++ -Wall -Wextra -fprofile-arcs Receive_Battery_Charging_Parameters.cpp test_Receive_Battery_Charging_Parameters.cpp -o testreceiver

      - name: run test
      run: ./testreceiver
      
      - name: build receiver
      run: g++ -Wall -Wextra -fprofile-arcs Receive_Battery_Charging_Parameters.cpp Receive_Battery_Charging_Parameters_Main.cpp -o receiver      
      
      - name: run receiver
      run: ./receiver
      
      -name: run sender
      run: java BatterySimulator.java


      - name: Build and Generate coverage
        run: 'mvn test jacoco:report'
      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./target/site/jacoco
          retention-days: 21

      




